### ISSUE TITLE
Add priority system

### ISSUE THREAD

**Issue by GabAlpha** [GabAlpha/basilk#1]
**Describe the feature**
It would be useful to integrate a priority system

**Describe your idea**
Make sure that each task has a configurable priority. This value will be used in sorting.

**Additional context**
Nope.

**Comment by dan-da** [comment]
I would suggest a simple move up/down mechanism.

eg, highlight entry, hit 'm' for move, and then up/down arrow to re-order.

**Comment by GabAlpha** [comment]
> I would suggest a simple move up/down mechanism.
> 
> eg, highlight entry, hit 'm' for move, and then up/down arrow to re-order.

This is a good idea! I was thinking about how the sorting logic could work. Currently, the sorting logic is as follows: read all tasks and display them by JSON array index. If a task has a _done_ status, it is moved to the end or if a task has a _ongoing_ status, it is moved to the beginning. With the new priority system, this value would override all other criteria. But how does this work with the move mechanism? 

I propose that the order of importance could be `priority`, then `done/ongoing status` and finally by `array index`. When you move a task, you move it into the JSON array. Only the _done_ status can override everything and always place the task last

#### examples
_They are written in order of how they would be displayed_

- priority: 1 | status: upnext | index (inside the json): 10 => **priority wins**
- priority: 1 | status: ongoing | index (inside the json): 2 => **index wins**
- priority: 2 | status: upnext | index (inside the json): 1 => **priority and status are even**
- priority: 0 | status: done | index (inside the json): 0 => **status wins**

The priority value (like the array index + 1) is in ascending order: 1 is the highest priority, and it increases up to 3
I hope I have been clear!

What do you think?

**Comment by dan-da** [comment]
I would suggest that sort and move/order are independent actions that can override eachother.

So then I can hit 'm' any number of times to re-order items to my liking.

Alternatively, I can hit 's' to sort items.  (up/down, by various criteria).

When I hit 's', it would warn that I will lose my custom orderings (if any were performed).

After sorting, I can again hit 'm' to re-order as I like.

**Comment by GabAlpha** [comment]
Sounds good for me, I'll split this issue into two parts. I will release the move feature in version 0.3.0
