### ISSUE TITLE
Add a GitHub workflow for automated testing, building, releasing, dependency upgrading, and security auditing

### ISSUE THREAD

**Issue by yonas** [GabAlpha/basilk#6]
A workflow could be triggered on push and PRs could check:

## Testing
- [ ] format linting
- [ ] `cargo build --release` doesn't fail
- [ ] `cargo test` doesn't fail

## Security
- [ ] [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) to notify when dependencies are outdated or have security vulnerabilities

## [Tools](https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/)
[cargo-deny](https://github.com/EmbarkStudios/cargo-deny) - lint dependencies
    [cargo-outdated](https://github.com/kbknapp/cargo-outdated) - find outdated dependencies
    [cargo-udeps](https://github.com/est31/cargo-udeps) - find unused dependencies
    [cargo-audit](https://github.com/RustSec/rustsec/tree/main/cargo-audit) - search for security vulnerabilities
    [cargo-pants](https://github.com/sonatype-nexus-community/cargo-pants) - search for security vulnerabilities (by [sonatype](https://ossindex.sonatype.org/) )

## Template Repo
https://github.com/yonasBSD/rust-ci-github-actions-workflow

**Comment by maximiliankolb** [comment]
I have started working on this with PR https://github.com/GabAlpha/basilk/pull/15 I would like to eventually expand the GHA to build and test.

**Comment by maximiliankolb** [comment]
Linting has been merged as part of https://github.com/GabAlpha/basilk/pull/15
