### ISSUE TITLE
Add vim visual movement.

### ISSUE THREAD

**Issue by sponkurtus2** [GabAlpha/basilk#8]
**Describe the feature**
You can currently move by using up/down/left/right arrows, but it'd be really nice to also be able to move with vim keys (h,j,k,l).

**Describe your idea**
Add vim basic visual mode keys to navigate.

**Additional context**
I'll try to help with a pull request. ^^

**Comment by GabAlpha** [comment]
Hi @sponkurtus2, thanks for your suggestion. I've created a [new commit](https://github.com/GabAlpha/basilk/commit/e23e11d646177fc721961a1c3b163a4ee5960b0c) for this and added the logic as follows:

- **View Projects:** Navigate with `h/j` keys, access tasks with `l`
- **View Tasks:** Navigate with `h/j` keys, access projects with `k`
- **Change Status:** Navigate with `h/j` keys.

Let me know if I've forgotten anything, or feel free to open a new PR for it!
